/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Hp' at '3/11/20 5:25 PM' with Gradle 3.0
 *
 * @author Hp, @date 3/11/20 5:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
